config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-listener:
      branch: main
      repo: https://gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-listener
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-listener git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-cerulean-terrier.sh
        container: qc.acc_thirsty-salmon-lynx
  QC.Doc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-listener find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-indigo-whale.sh
        container: qc.doc_slimy-copper-mandrill
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-listener git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-copper-earwig.sh
        container: qc.doc_woolly-yellow-camel
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-listener markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-xanthic-olm.sh
        container: qc.doc_tasty-asparagus-chicken
  QC.Lic:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-listener licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-chocolate-beetle.sh
        container: qc.lic_ugly-violet-buzzard
  QC.Sec:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-listener bandit:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-emerald-gopher.sh
        container: qc.sec_clammy-tan-swan
  QC.Sty:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-listener flake8:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-blue-bulldog.sh
        container: qc.sty_chewy-tomato-sheepdog
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-listener jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-azure-neanderthal.sh
        container: qc.sty_gloppy-indigo-corgi
  QC.Uni:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-listener pytest:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-green-guppy.sh
        container: qc.uni_skimpy-razzmatazz-beetle
  QC.Ver:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/meteo-listener get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-auburn-husky.sh
        container: qc.ver_snappy-tomato-mongoose
timeout: 5400
